title: Peter Taing
logo: /assets/img/headshot.jpg
description: Passionate data analyst with expertise in R, Python, SQL, and statistical analysis. Experienced in leveraging data to drive business insights and decision-making. Skilled in data visualization and machine learning techniques.
#show_downloads: true
theme: jekyll-theme-minimal
